# Generated by Django 5.2.2 on 2025-07-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edu_date', models.CharField(max_length=50)),
                ('Edu_title', models.CharField(max_length=50)),
                ('Edu_Desc', models.TextField()),
            ],
        ),
    ]
