# Generated by Django 5.2.2 on 2025-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Edu_title',
            field=models.CharField(max_length=100),
        ),
    ]
