# Generated by Django 5.2.2 on 2025-07-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enqData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enqdata',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='enqdata',
            old_name='message',
            new_name='messageData',
        ),
        migrations.RenameField(
            model_name='enqdata',
            old_name='name',
            new_name='nameFirst',
        ),
    ]
